AWSTemplateFormatVersion: '2010-09-09'
Description: EFS filesystem, mounts, access points for integration with AWS Lambda
Transform: AWS::Serverless-2016-10-31
Parameters:
  pVpcId:
    Type: String
  pSubnetIds:
    Type: List<String>
Resources:
  SGroupLambda:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: sg-lambda
      VpcId: !Ref pVpcId
  SGroupEFS:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: sg-efs
      SecurityGroupIngress:
        SourceSecurityGroupId: !Ref SGroupLambda
        FromPort: 2049
        IpProtocol: tcp
        ToPort: 2049
      VpcId: !Ref pVpcId
  Share:
    Type: AWS::EFS::FileSystem
    Properties:
      PerformanceMode: generalPurpose
  Mount0:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !GetAtt Share.FileSystemId
      SecurityGroups:
        - !Ref SGroupEFS
      SubnetId: !Select [0, !Ref pSubnetIds]
  Mount1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !GetAtt Share.FileSystemId
      SecurityGroups:
        - !Ref SGroupEFS
      SubnetId: !Select [1, !Ref pSubnetIds]
  AccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: !GetAtt Share.FileSystemId
      PosixUser:
        Uid: 0
        Gid: 0
      RootDirectory:
        CreationInfo:
          OwnerUid: 0
          OwnerGid: 0
          Permissions: "0777"
        Path: /efs
Outputs:
  outShare:
    Value: !Ref Share
  outShareArn:
    Value: !GetAtt Share.Arn
  outShareId:
    Value: !GetAtt Share.FileSystemId
  outSGroupLambda:
    Value: !Ref SGroupLambda
  outSGroupEFS:
    Value: !Ref SGroupEFS
  outMount0:
    Value: !Ref Mount0
  outMount1:
    Value: !Ref Mount1
  outAccessPointArn:
    Value: !GetAtt AccessPoint.Arn